### ISSUE TITLE
Consistently use English language throughout project

### ISSUE THREAD

**Issue by yeckey** [Kengstar/messeShowcase#12]
There are some occurences of German in the frontend and the Node-RED nodes.
German localization might be added later as an option.

**Comment by yeckey** [comment]
Is there any way to add localization data in Node-RED custom nodes?

**Comment by yeckey** [comment]
https://github.com/node-red/node-red/wiki/Design:-i18n

**Comment by Kengstar** [comment]
there is an example for integrating i18n here: https://github.com/node-red/node-red-nodes/tree/master/social/twitter . Use this as baseline i guess

**Comment by Kengstar** [comment]
https://groups.google.com/forum/#!topic/node-red/FqSk56XoiBg

**Comment by Kengstar** [comment]
fixed by #28
